// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Announcement is the golang structure of table announcement for DAO operations like Where/Data.
type Announcement struct {
	g.Meta     `orm:"table:announcement, do:true"`
	Id         interface{} // ID
	Title      interface{} // Title
	Content    interface{} // Content
	UpdateTime *gtime.Time // Update time
	UserId     interface{} // User ID
	Images     interface{} //
}
