// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Bank is the golang structure of table bank for DAO operations like Where/Data.
type Bank struct {
	g.Meta `orm:"table:bank, do:true"`
	Id     interface{} // ID
	Name   interface{} // Bank name
}
