// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// CommentResponse is the golang structure of table comment_response for DAO operations like Where/Data.
type CommentResponse struct {
	g.Meta           `orm:"table:comment_response, do:true"`
	Id               interface{} // ID
	ParentResponseId interface{} // PARENT_RESPONSE_ID
	Title            interface{} // title
	Content          interface{} // content
	UserId           interface{} // USER_ID
	CreatTime        *gtime.Time // creat_time
}
