// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Credit is the golang structure of table credit for DAO operations like Where/Data.
type Credit struct {
	g.Meta `orm:"table:credit, do:true"`
	Id     interface{} // ID
	UserId interface{} // User ID
	Credit interface{} // Credit of User
}
