// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// FacilityScore is the golang structure of table facility_score for DAO operations like Where/Data.
type FacilityScore struct {
	g.Meta     `orm:"table:facility_score, do:true"`
	FacilityId interface{} // Facility ID
	Score      interface{} // Current Score
}
