// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Payment is the golang structure of table payment for DAO operations like Where/Data.
type Payment struct {
	g.Meta      `orm:"table:payment, do:true"`
	Id          interface{} // ID
	WalletId    interface{} // Wallet ID
	OrderId     interface{} // Order ID
	PaymentCode interface{} // Payment code
	Time        *gtime.Time // Payment Time
	Amount      interface{} // Payment Amount
	PaymentType interface{} // Payment type
	Status      interface{} // Payment status
}
