// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// SubscriptionType is the golang structure of table subscription_type for DAO operations like Where/Data.
type SubscriptionType struct {
	g.Meta      `orm:"table:subscription_type, do:true"`
	Id          interface{} //
	Name        interface{} //
	Amount      interface{} //
	Days        interface{} //
	Permissions interface{} //
}
