// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// SubscriptionPermission is the golang structure of table subscription_permission for DAO operations like Where/Data.
type SubscriptionPermission struct {
	g.Meta      `orm:"table:subscription_permission, do:true"`
	Id          interface{} //
	Name        interface{} // name
	Description interface{} //
}
