// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TopicComment is the golang structure of table topic_comment for DAO operations like Where/Data.
type TopicComment struct {
	g.Meta          `orm:"table:topic_comment, do:true"`
	Id              interface{} // ID
	UserId          interface{} // USER_ID
	TopicId         interface{} // TOPIC_ID
	ParentCommentId interface{} // Parent comment ID
	Title           interface{} // Comment_title
	Content         interface{} // Comment_conrtent
	Approve         interface{} // comment_approve
	Disapprove      interface{} // comment_disapprove
	UpdateTime      *gtime.Time // creat_time
	Images          interface{} // Image urls
}
