// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Topics is the golang structure of table topics for DAO operations like Where/Data.
type Topics struct {
	g.Meta          `orm:"table:topics, do:true"`
	Id              interface{} // ID
	UserId          interface{} // USER_ID
	Content         interface{} // content
	Title           interface{} // title
	UpdateTime      *gtime.Time // time
	ApproveCount    interface{} // Approve count
	DisapproveCount interface{} // Disapprove count
	Images          interface{} // Image urls
	Videos          interface{} // Video urls
}
