// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TopicApproves is the golang structure of table topic_approves for DAO operations like Where/Data.
type TopicApproves struct {
	g.Meta     `orm:"table:topic_approves, do:true"`
	Id         interface{} // ID
	UserId     interface{} // USER_ID
	TopicId    interface{} // TOPIC_ID
	Type       interface{} // TYPE
	UpdateTime *gtime.Time // create_time
}
