// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure of table user for DAO operations like Where/Data.
type User struct {
	g.Meta     `orm:"table:user, do:true"`
	Id         interface{} // USER ID
	Username   interface{} // USERNAME
	Password   interface{} // PASSWORD
	Avatar     interface{} // AVATAR URL
	Email      interface{} // EMAIL ADDRESS
	Phone      interface{} // PHONE NUMBER
	Gender     interface{} // GENDER
	UpdateTime *gtime.Time // CREATE AT
	Role       interface{} // ROLE
	LoginTime  *gtime.Time // LAST LOGIN TIME
	IsCoach    interface{} //
}
