// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// WalletCard is the golang structure of table wallet_card for DAO operations like Where/Data.
type WalletCard struct {
	g.Meta      `orm:"table:wallet_card, do:true"`
	Id          interface{} // ID
	BankId      interface{} // Bank ID of the card
	WalletId    interface{} // Wallet ID of the card
	CardAccount interface{} // Card number
	Phone       interface{} // Phone of the card
	Amount      interface{} // Money amount
}
