server:
  address:     ":8000"
  openapiPath: "/api.json"
#  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true
  path  : "logs/app/"

database:
  logger:
    path:    "logs/sql/"
    level:   "all"

  default:
    link:   "mysql:root:2332@tcp(172.17.0.3:3306)/gym?charset=utf8mb4&parseTime=True&loc=Local"
    debug:  true

redis:
  default:
    address: "172.17.0.11:6379"

mail:
  host:     "smtp.163.com"
  port:     465
  username: "15169904338@163.com"
  password: "ZXXGRQPZPGNBXNVT"

upload:
  defaultAvatar: "default.png"
  path: "uploads/"
  defaultAvatarBase64: "iVBORw0KGgoAAAANSUhEUgAAAEgAAABICAMAAABiM0N1AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAABaUExURUdwTLYNA/8+MP83KbwPBbkNA8APBLcNBLgNA78QBf5EN/0sH84SB9oXDPxNQfMiFvtYTLILBMMPBecbEPxkWf18cv6LgvtvZf+clP+uqP/Evv/49f/c1+kxJYbABGgAAAAKdFJOUwCM//88Z8kbsOKu4QufAAAEfElEQVRYw+WY52KzOgyGg9kYswyEEHz/t3kkeRPytU3774hsxONXsjzI7fY/sTLLq6IuqiQvy3cueaJdsvI9Ji+maWrbVrTtVOTllUdFDnB+morkDSqpkSFk33OulGyL/OwBDQmhFOe8lxJaq5MrORU0JXo2r+u2LkOTctlW5clDKM6GZQNbhrQXoDt74dSIGbbjSXY8lo6lMvQrC8TcH87jnkoQlb1wRN9s5KEdn/udMeX9sho48/4MbB9AVEwqC5SzPw9tO748j42ljgQcyddDe9jGjhlJYfxJK+SwHzvaY7d2bGkvNQniknw7DnfKtDVDdJXnZFMrOkA42+AA2zcuBeYJOf1GDjserrVjgIz73q1AEFy70TO0x9oLAS1WQvSrbcM2g9T9oURblF5QO0QAqABt2wL1kmVtK+8P/DluBoH3QBJUkFhWb4t+LuuyLOsgRQ1dMWyBw4otWZxqJ5slKCEVUJbYmABT9huc1S1Z5Da4jqPIosvvkSkYNjN+oFOBmyb52HKI7E4ed0LM+Ji9DVJ25uN99nwnUbaTHnMJgqz5y+fBmlL0FrBn3R7BVmVLCXKtAkpAQOu6oWk6eLU2DxFvWQBUmCqalAnGX47H2aIGBotaOltJpMhjQkLTNc4srdPN4GMgUgRylNBCDICak75O67o3woSWTJPQmQnEeAgju0LpYKE8TLJzAHk5ntAFHGZFNeRBXp3ugxlAiZlqJtEZjgV0kZwQ1ZzyNsAYas1gqyFJDuONIcahGtZcGKYKBmPpBq3yGOYPFiliUQtGZNcxmLLsKgNrlWpU51wadqIYKrIiOHzveinsqlSOAFKAahScUuwECD77byka/YoTll+wYMVSDBFpcOGJ4VOWasN3hpOxm/4pNrA0BRqcVCGrYUG4AcYYRJYHqxpJSpVrCpWlUTJ8TJrE8QEH9FmwskFxt0BSXHFPY1dRGozh4CZABMvRLRtBklSwe+AOk1pJTZB1J4dr64NUa0nQcbgPwa2G4ja+QFHDTiCN0qtVtPYbEu/RyfRJFFhDWUsjRSBoOu0i8tGQetz+cJ/yuJxIURTYeYtUFpQmJLlEvfZanCLk1C+7tkxLspo8KhoZMUeG636Qb0eysbkBZUlake73Hnds1dXer4hIHvUyOEgO6akvt6MQ3Ng6UhxZWEfcgMQ0Ztfb2jwicTe+g8nJxSWRk7zbaFcUXEDycyzT064P7E2CojQRSUs6B2c4uMt+kyBX4KEmE5udf60gzXmXIJ+mS01NwKG4xvzftzVXpKAaPSf56gYpiUku4zZBOq4p+fpWC7vuNbpYzz86LLx3QUmRpvTMKcrbT0lutIRxfY9jiyDQxLkpQ62nzr57R5rVZ03c1WH7A86Z1Nth+kM9diYwJEL1hEHOV4V4XZiaJAlDnPGnHL0aEIlQhPmIE2gyhmGNySf/JujBQrfwoiU5n3EMSf9fQHI+5VjSRP87/IZDAxhJhBmr8nMQaRoJ8zvOrSTS7zl6KvgLjiX9nqNJf8HB1a7+Ew6Q/ojzPfsPi9abCp3Zym4AAAAASUVORK5CYII="

receipt:
  path: "receipts/"
  pdfPath: "receipts/pdf/"
  qrPath:  "receipts/qr/"

timeZone: "Asia/Shanghai"

# JUST ADD IT TO THE CUSTOM CONFIGURATION
customConfigUpdate: 1 # 0 - Dont update when start up
# 1 - Update when start up
customConfig:
  OpenTime:
    Value: "08:00"
    Type: "time"
  CloseTime:
    Value: "22:00"
    Type: "time"

  Subscription:
    Value: "10"
    Type: "string"