// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// FacilityDao is the data access object for table facility.
type FacilityDao struct {
	table   string          // table is the underlying table name of the DAO.
	group   string          // group is the database configuration group name of current DAO.
	columns FacilityColumns // columns contains all the column names of Table for convenient usage.
}

// FacilityColumns defines and stores column names for table facility.
type FacilityColumns struct {
	Id          string // Facility ID
	Name        string // Facility Name
	Description string // Facility Description
	Location    string // Facility Location
	Images      string // Image urls
	Tags        string //
	Lat         string //
	Long        string //
}

// facilityColumns holds the columns for table facility.
var facilityColumns = FacilityColumns{
	Id:          "id",
	Name:        "name",
	Description: "description",
	Location:    "location",
	Images:      "images",
	Tags:        "tags",
	Lat:         "lat",
	Long:        "long",
}

// NewFacilityDao creates and returns a new DAO object for table data access.
func NewFacilityDao() *FacilityDao {
	return &FacilityDao{
		group:   "default",
		table:   "facility",
		columns: facilityColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *FacilityDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *FacilityDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *FacilityDao) Columns() FacilityColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *FacilityDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *FacilityDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *FacilityDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
