// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SubscriptionTypeDao is the data access object for table subscription_type.
type SubscriptionTypeDao struct {
	table   string                  // table is the underlying table name of the DAO.
	group   string                  // group is the database configuration group name of current DAO.
	columns SubscriptionTypeColumns // columns contains all the column names of Table for convenient usage.
}

// SubscriptionTypeColumns defines and stores column names for table subscription_type.
type SubscriptionTypeColumns struct {
	Id          string //
	Name        string //
	Amount      string //
	Days        string //
	Permissions string //
}

// subscriptionTypeColumns holds the columns for table subscription_type.
var subscriptionTypeColumns = SubscriptionTypeColumns{
	Id:          "id",
	Name:        "name",
	Amount:      "amount",
	Days:        "days",
	Permissions: "permissions",
}

// NewSubscriptionTypeDao creates and returns a new DAO object for table data access.
func NewSubscriptionTypeDao() *SubscriptionTypeDao {
	return &SubscriptionTypeDao{
		group:   "default",
		table:   "subscription_type",
		columns: subscriptionTypeColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SubscriptionTypeDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SubscriptionTypeDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *SubscriptionTypeDao) Columns() SubscriptionTypeColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *SubscriptionTypeDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SubscriptionTypeDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SubscriptionTypeDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
