// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// WalletCardDao is the data access object for table wallet_card.
type WalletCardDao struct {
	table   string            // table is the underlying table name of the DAO.
	group   string            // group is the database configuration group name of current DAO.
	columns WalletCardColumns // columns contains all the column names of Table for convenient usage.
}

// WalletCardColumns defines and stores column names for table wallet_card.
type WalletCardColumns struct {
	Id          string // ID
	BankId      string // Bank ID of the card
	WalletId    string // Wallet ID of the card
	CardAccount string // Card number
	Phone       string // Phone of the card
	Amount      string // Money amount
}

// walletCardColumns holds the columns for table wallet_card.
var walletCardColumns = WalletCardColumns{
	Id:          "id",
	BankId:      "bank_id",
	WalletId:    "wallet_id",
	CardAccount: "card_account",
	Phone:       "phone",
	Amount:      "amount",
}

// NewWalletCardDao creates and returns a new DAO object for table data access.
func NewWalletCardDao() *WalletCardDao {
	return &WalletCardDao{
		group:   "default",
		table:   "wallet_card",
		columns: walletCardColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *WalletCardDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *WalletCardDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *WalletCardDao) Columns() WalletCardColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *WalletCardDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *WalletCardDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *WalletCardDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
