// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Gym-backend/internal/dao/internal"
)

// internalAnnouncementDao is internal type for wrapping internal DAO implements.
type internalAnnouncementDao = *internal.AnnouncementDao

// announcementDao is the data access object for table announcement.
// You can define custom methods on it to extend its functionality as you wish.
type announcementDao struct {
	internalAnnouncementDao
}

var (
	// Announcement is globally public accessible object for table announcement operations.
	Announcement = announcementDao{
		internal.NewAnnouncementDao(),
	}
)

// Fill with you ideas below.
