// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Gym-backend/internal/dao/internal"
)

// internalBankDao is internal type for wrapping internal DAO implements.
type internalBankDao = *internal.BankDao

// bankDao is the data access object for table bank.
// You can define custom methods on it to extend its functionality as you wish.
type bankDao struct {
	internalBankDao
}

var (
	// Bank is globally public accessible object for table bank operations.
	Bank = bankDao{
		internal.NewBankDao(),
	}
)

// Fill with you ideas below.
