// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Gym-backend/internal/dao/internal"
)

// internalFacilityImageDao is internal type for wrapping internal DAO implements.
type internalFacilityImageDao = *internal.FacilityImageDao

// facilityImageDao is the data access object for table facility_image.
// You can define custom methods on it to extend its functionality as you wish.
type facilityImageDao struct {
	internalFacilityImageDao
}

var (
	// FacilityImage is globally public accessible object for table facility_image operations.
	FacilityImage = facilityImageDao{
		internal.NewFacilityImageDao(),
	}
)

// Fill with you ideas below.
