// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Gym-backend/internal/dao/internal"
)

// internalFacilityDao is internal type for wrapping internal DAO implements.
type internalFacilityDao = *internal.FacilityDao

// facilityDao is the data access object for table facility.
// You can define custom methods on it to extend its functionality as you wish.
type facilityDao struct {
	internalFacilityDao
}

var (
	// Facility is globally public accessible object for table facility operations.
	Facility = facilityDao{
		internal.NewFacilityDao(),
	}
)

// Fill with you ideas below.
