// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Gym-backend/internal/dao/internal"
)

// internalFacilityPlaceDao is internal type for wrapping internal DAO implements.
type internalFacilityPlaceDao = *internal.FacilityPlaceDao

// facilityPlaceDao is the data access object for table facility_place.
// You can define custom methods on it to extend its functionality as you wish.
type facilityPlaceDao struct {
	internalFacilityPlaceDao
}

var (
	// FacilityPlace is globally public accessible object for table facility_place operations.
	FacilityPlace = facilityPlaceDao{
		internal.NewFacilityPlaceDao(),
	}
)

// Fill with you ideas below.
