// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Gym-backend/internal/dao/internal"
)

// internalFacilityScoreDao is internal type for wrapping internal DAO implements.
type internalFacilityScoreDao = *internal.FacilityScoreDao

// facilityScoreDao is the data access object for table facility_score.
// You can define custom methods on it to extend its functionality as you wish.
type facilityScoreDao struct {
	internalFacilityScoreDao
}

var (
	// FacilityScore is globally public accessible object for table facility_score operations.
	FacilityScore = facilityScoreDao{
		internal.NewFacilityScoreDao(),
	}
)

// Fill with you ideas below.
