// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Gym-backend/internal/dao/internal"
)

// internalReceiptDao is internal type for wrapping internal DAO implements.
type internalReceiptDao = *internal.ReceiptDao

// receiptDao is the data access object for table receipt.
// You can define custom methods on it to extend its functionality as you wish.
type receiptDao struct {
	internalReceiptDao
}

var (
	// Receipt is globally public accessible object for table receipt operations.
	Receipt = receiptDao{
		internal.NewReceiptDao(),
	}
)

// Fill with you ideas below.
