// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Gym-backend/internal/dao/internal"
)

// internalTopicsDao is internal type for wrapping internal DAO implements.
type internalTopicsDao = *internal.TopicsDao

// topicsDao is the data access object for table topics.
// You can define custom methods on it to extend its functionality as you wish.
type topicsDao struct {
	internalTopicsDao
}

var (
	// Topics is globally public accessible object for table topics operations.
	Topics = topicsDao{
		internal.NewTopicsDao(),
	}
)

// Fill with you ideas below.
