// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Gym-backend/internal/dao/internal"
)

// internalTopicApprovesDao is internal type for wrapping internal DAO implements.
type internalTopicApprovesDao = *internal.TopicApprovesDao

// topicApprovesDao is the data access object for table topic_approves.
// You can define custom methods on it to extend its functionality as you wish.
type topicApprovesDao struct {
	internalTopicApprovesDao
}

var (
	// TopicApproves is globally public accessible object for table topic_approves operations.
	TopicApproves = topicApprovesDao{
		internal.NewTopicApprovesDao(),
	}
)

// Fill with you ideas below.
