// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Gym-backend/internal/dao/internal"
)

// internalTopicCommentDao is internal type for wrapping internal DAO implements.
type internalTopicCommentDao = *internal.TopicCommentDao

// topicCommentDao is the data access object for table topic_comment.
// You can define custom methods on it to extend its functionality as you wish.
type topicCommentDao struct {
	internalTopicCommentDao
}

var (
	// TopicComment is globally public accessible object for table topic_comment operations.
	TopicComment = topicCommentDao{
		internal.NewTopicCommentDao(),
	}
)

// Fill with you ideas below.
