// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Gym-backend/internal/dao/internal"
)

// internalWalletCardDao is internal type for wrapping internal DAO implements.
type internalWalletCardDao = *internal.WalletCardDao

// walletCardDao is the data access object for table wallet_card.
// You can define custom methods on it to extend its functionality as you wish.
type walletCardDao struct {
	internalWalletCardDao
}

var (
	// WalletCard is globally public accessible object for table wallet_card operations.
	WalletCard = walletCardDao{
		internal.NewWalletCardDao(),
	}
)

// Fill with you ideas below.
