
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  gen:
    dao:
      - link:     "mysql:root:2332@tcp(172.250.0.233:3306)/gym"
#        tables:   "user,facility,facility_image"
        jsonCase: "CamelLower"

