// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "Gym-backend/internal/logic/announcement"
	_ "Gym-backend/internal/logic/bank"
	_ "Gym-backend/internal/logic/bizctx"
	_ "Gym-backend/internal/logic/cache"
	_ "Gym-backend/internal/logic/card"
	_ "Gym-backend/internal/logic/config"
	_ "Gym-backend/internal/logic/course"
	_ "Gym-backend/internal/logic/credit"
	_ "Gym-backend/internal/logic/evaluation"
	_ "Gym-backend/internal/logic/facility"
	_ "Gym-backend/internal/logic/file"
	_ "Gym-backend/internal/logic/middleware"
	_ "Gym-backend/internal/logic/notice"
	_ "Gym-backend/internal/logic/order"
	_ "Gym-backend/internal/logic/payment"
	_ "Gym-backend/internal/logic/place"
	_ "Gym-backend/internal/logic/receipt"
	_ "Gym-backend/internal/logic/session"
	_ "Gym-backend/internal/logic/subscription"
	_ "Gym-backend/internal/logic/system"
	_ "Gym-backend/internal/logic/tag"
	_ "Gym-backend/internal/logic/user"
	_ "Gym-backend/internal/logic/visualize"
	_ "Gym-backend/internal/logic/wallet"
)
