// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"Gym-backend/internal/model"
	"Gym-backend/internal/model/entity"
	"context"
)

type (
	IAnnouncement interface {
		GetAnnouncements(ctx context.Context) (announcements []*entity.Announcement, err error)
		AddAnnouncement(ctx context.Context, input *model.AddAnnouncement) error
		DeleteAnnouncement(ctx context.Context, id int) error
		ModifyAnnouncement(ctx context.Context, input *model.ModifyAnnouncement) error
	}
)

var (
	localAnnouncement IAnnouncement
)

func Announcement() IAnnouncement {
	if localAnnouncement == nil {
		panic("implement not found for interface IAnnouncement, forgot register?")
	}
	return localAnnouncement
}

func RegisterAnnouncement(i IAnnouncement) {
	localAnnouncement = i
}
