// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"Gym-backend/internal/model"
	"Gym-backend/internal/model/entity"
	"context"
)

type (
	IBank interface {
		GetBanks(ctx context.Context) (banks []*entity.Bank, err error)
		GetBankById(ctx context.Context, bankId int) (bank *entity.Bank, err error)
		AddBank(ctx context.Context, form *model.AddBankForm) error
		ValidateBankName(ctx context.Context, name string) error
		UpdateBank(ctx context.Context, form *model.UpdateBankForm) error
		DeleteBank(ctx context.Context, bankId int) error
	}
)

var (
	localBank IBank
)

func Bank() IBank {
	if localBank == nil {
		panic("implement not found for interface IBank, forgot register?")
	}
	return localBank
}

func RegisterBank(i IBank) {
	localBank = i
}
