// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
)

type (
	ICache interface {
		Get(ctx context.Context, key string) (interface{}, error)
		GetList(ctx context.Context, key string) (interface{}, error)
		Set(ctx context.Context, key string, value interface{}, expire int) error
		Push(ctx context.Context, key string, value interface{}) error
		Delete(ctx context.Context, key string) error
	}
)

var (
	localCache ICache
)

func Cache() ICache {
	if localCache == nil {
		panic("implement not found for interface ICache, forgot register?")
	}
	return localCache
}

func RegisterCache(i ICache) {
	localCache = i
}
