// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"Gym-backend/internal/model"
	"Gym-backend/internal/model/entity"
	"context"
)

type (
	IConfig interface {
		InitConfigToCache(ctx context.Context) error
		GetConfig(ctx context.Context) (res []*entity.Config, err error)
		GetConfigByKey(ctx context.Context, key string) (res *entity.Config, err error)
		UpdateConfig(ctx context.Context, config *model.Config) (err error)
		DeleteConfig(ctx context.Context, id int) (err error)
		CreateConfig(ctx context.Context, config *model.Config) (err error)
	}
)

var (
	localConfig IConfig
)

func Config() IConfig {
	if localConfig == nil {
		panic("implement not found for interface IConfig, forgot register?")
	}
	return localConfig
}

func RegisterConfig(i IConfig) {
	localConfig = i
}
