// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"Gym-backend/internal/model"
	"Gym-backend/internal/model/entity"
	"context"
)

type (
	ICourse interface {
		GetCourseList(ctx context.Context) (res []*entity.Course, err error)
		AddCourse(ctx context.Context, form *model.AddCourseForm) (err error)
		GetCourseById(ctx context.Context, id int) (res *entity.Course, err error)
	}
)

var (
	localCourse ICourse
)

func Course() ICourse {
	if localCourse == nil {
		panic("implement not found for interface ICourse, forgot register?")
	}
	return localCourse
}

func RegisterCourse(i ICourse) {
	localCourse = i
}
