// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"Gym-backend/internal/model/entity"
	"context"
)

type (
	ICredit interface {
		GetCredit(ctx context.Context) (credit *entity.Credit, err error)
		UpdateAmount(ctx context.Context, amount int) error
		GetAllCredit(ctx context.Context) (credits []*entity.Credit, err error)
		GetCreditByUserId(ctx context.Context, userId int) (credit *entity.Credit, err error)
		UpdateCreditByUserId(ctx context.Context, userId int, amount int) error
		CreateCreditForUser(ctx context.Context, userId int) error
	}
)

var (
	localCredit ICredit
)

func Credit() ICredit {
	if localCredit == nil {
		panic("implement not found for interface ICredit, forgot register?")
	}
	return localCredit
}

func RegisterCredit(i ICredit) {
	localCredit = i
}
