// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"Gym-backend/internal/model"
	"Gym-backend/internal/model/entity"
	"context"
)

type (
	IPayment interface {
		CreatePaymentForRegularOrder(ctx context.Context, form *model.CreatePaymentForm) (response *model.ResponsePaymentForm, err error)
		CreatePayment(ctx context.Context, form *model.CreatePaymentForm) (response *model.ResponsePaymentForm, err error)
		CreatePaymentForRefund(ctx context.Context, form *model.RefundPaymentForm) error
		GeneratePaymentCode() string
		GetPaymentByPaymentCode(ctx context.Context, paymentCode string) (payment *entity.Payment, err error)
		GetPaymentById(ctx context.Context, paymentId int) (payment *entity.Payment, err error)
		GetPaymentByOrderId(ctx context.Context, orderId int) (payment *entity.Payment, err error)
		GetPaymentByUserId(ctx context.Context, userId int) (payment []*entity.Payment, err error)
		GetAllPayment(ctx context.Context) (payments []*entity.Payment, err error)
		GetPaymentByOrderCode(ctx context.Context, orderCode string) (payment *entity.Payment, err error)
		UpdatePaymentStatus(ctx context.Context, paymentId int, status int) (err error)
		UpdatePaymentStatusByOrderId(ctx context.Context, orderId int, status int) error
	}
)

var (
	localPayment IPayment
)

func Payment() IPayment {
	if localPayment == nil {
		panic("implement not found for interface IPayment, forgot register?")
	}
	return localPayment
}

func RegisterPayment(i IPayment) {
	localPayment = i
}
