// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"Gym-backend/internal/model"
	"Gym-backend/internal/model/entity"
	"context"
)

type (
	IReceipt interface {
		GetReceiptByOrderId(ctx context.Context, orderId int) (receipt *entity.Receipt, err error)
		AddReceipt(ctx context.Context, input model.CreateReceiptForm) (err error)
		SendReceiptToUser(ctx context.Context, orderCode string) (err error)
		DeleteReceipt(ctx context.Context, id int) error
	}
)

var (
	localReceipt IReceipt
)

func Receipt() IReceipt {
	if localReceipt == nil {
		panic("implement not found for interface IReceipt, forgot register?")
	}
	return localReceipt
}

func RegisterReceipt(i IReceipt) {
	localReceipt = i
}
