// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/gogf/gf/v2/os/gtime"
)

type (
	ISystem interface {
		GetLogs(ctx context.Context, date *gtime.Time) (res string, err error)
		GetSqlLogs(ctx context.Context, date *gtime.Time) (res string, err error)
		GetLogsList(ctx context.Context) (res []string, err error)
	}
)

var (
	localSystem ISystem
)

func System() ISystem {
	if localSystem == nil {
		panic("implement not found for interface ISystem, forgot register?")
	}
	return localSystem
}

func RegisterSystem(i ISystem) {
	localSystem = i
}
