// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"Gym-backend/internal/model/entity"
	"context"
)

type (
	ITag interface {
		CreateNewTag(ctx context.Context, name string) (err error)
		DeleteTag(ctx context.Context, tagId int) (err error)
		GetAllTags(ctx context.Context) (res []*entity.Tag, err error)
		GetTagById(ctx context.Context, id int) (res *entity.Tag, err error)
		GetTagByName(ctx context.Context, name string) (res *entity.Tag, err error)
	}
)

var (
	localTag ITag
)

func Tag() ITag {
	if localTag == nil {
		panic("implement not found for interface ITag, forgot register?")
	}
	return localTag
}

func RegisterTag(i ITag) {
	localTag = i
}
