// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Bank is the golang structure for table bank.
type Bank struct {
	Id   int    `json:"id"   ` // ID
	Name string `json:"name" ` // Bank name
}
