// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// CommentResponse is the golang structure for table comment_response.
type CommentResponse struct {
	Id               int         `json:"id"               ` // ID
	ParentResponseId int         `json:"parentResponseId" ` // PARENT_RESPONSE_ID
	Title            string      `json:"title"            ` // title
	Content          string      `json:"content"          ` // content
	UserId           int         `json:"userId"           ` // USER_ID
	CreatTime        *gtime.Time `json:"creatTime"        ` // creat_time
}
