// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Config is the golang structure for table config.
type Config struct {
	Id    int    `json:"id"    ` //
	Key   string `json:"key"   ` //
	Value string `json:"value" ` //
	Type  string `json:"type"  ` //
}
