// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Course is the golang structure for table course.
type Course struct {
	Id          int    `json:"id"          ` //
	Title       string `json:"title"       ` //
	Description string `json:"description" ` //
	Video       string `json:"video"       ` //
	Image       string `json:"image"       ` //
}
