// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Credit is the golang structure for table credit.
type Credit struct {
	Id     int `json:"id"     ` // ID
	UserId int `json:"userId" ` // User ID
	Credit int `json:"credit" ` // Credit of User
}
