// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// FacilityImage is the golang structure for table facility_image.
type FacilityImage struct {
	Id         int         `json:"id"         ` //
	Path       string      `json:"path"       ` //
	UploadTime *gtime.Time `json:"uploadTime" ` //
	FacilityID int         `json:"facilityID" ` //
}
