// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// FacilityPlace is the golang structure for table facility_place.
type FacilityPlace struct {
	Id          int     `json:"id"          ` // ID
	FacilityId  int     `json:"facilityId"  ` // Facility ID
	Name        string  `json:"name"        ` // Place Name
	Description string  `json:"description" ` // Place Description
	Cost        float64 `json:"cost"        ` // Place order code
}
