// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// FacilityScore is the golang structure for table facility_score.
type FacilityScore struct {
	FacilityId int     `json:"facilityId" ` // Facility ID
	Score      float64 `json:"score"      ` // Current Score
}
