// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Order is the golang structure for table order.
type Order struct {
	Id              int         `json:"id"              ` // ID
	UserId          int         `json:"userId"          ` // User id
	PlaceId         int         `json:"placeId"         ` // Place ID
	Time            *gtime.Time `json:"time"            ` // Order Time
	StartTime       *gtime.Time `json:"startTime"       ` // Start time of the order
	EndTime         *gtime.Time `json:"endTime"         ` // End time of the order
	Amount          float64     `json:"amount"          ` // Amount of the order
	OrderCode       string      `json:"orderCode"       ` // Order code
	Status          int         `json:"status"          ` // Status of the order
	Discount        float64     `json:"discount"        ` //
	ParentOrderCode string      `json:"parentOrderCode" ` //
}
