// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Subscription is the golang structure for table subscription.
type Subscription struct {
	Id               int         `json:"id"               ` // ID
	UserId           int         `json:"userId"           ` //
	StartTime        *gtime.Time `json:"startTime"        ` //
	EndTime          *gtime.Time `json:"endTime"          ` //
	SubscriptionType int         `json:"subscriptionType" ` //
	Status           int         `json:"status"           ` //
}
