// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// SubscriptionType is the golang structure for table subscription_type.
type SubscriptionType struct {
	Id          int     `json:"id"          ` //
	Name        string  `json:"name"        ` //
	Amount      float64 `json:"amount"      ` //
	Days        int     `json:"days"        ` //
	Permissions string  `json:"permissions" ` //
}
