// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// SubscriptionPermission is the golang structure for table subscription_permission.
type SubscriptionPermission struct {
	Id          int    `json:"id"          ` //
	Name        string `json:"name"        ` // name
	Description string `json:"description" ` //
}
