// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Tag is the golang structure for table tag.
type Tag struct {
	Id   int    `json:"id"   ` //
	Name string `json:"name" ` //
}
