// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Topics is the golang structure for table topics.
type Topics struct {
	Id              int         `json:"id"              ` // ID
	UserId          int         `json:"userId"          ` // USER_ID
	Content         string      `json:"content"         ` // content
	Title           string      `json:"title"           ` // title
	UpdateTime      *gtime.Time `json:"updateTime"      ` // time
	ApproveCount    int         `json:"approveCount"    ` // Approve count
	DisapproveCount int         `json:"disapproveCount" ` // Disapprove count
	Images          string      `json:"images"          ` // Image urls
	Videos          string      `json:"videos"          ` // Video urls
}
