// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// TopicApproves is the golang structure for table topic_approves.
type TopicApproves struct {
	Id         int         `json:"id"         ` // ID
	UserId     int         `json:"userId"     ` // USER_ID
	TopicId    int         `json:"topicId"    ` // TOPIC_ID
	Type       int         `json:"type"       ` // TYPE
	UpdateTime *gtime.Time `json:"updateTime" ` // create_time
}
