// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id         int         `json:"id"         ` // USER ID
	Username   string      `json:"username"   ` // USERNAME
	Password   string      `json:"password"   ` // PASSWORD
	Avatar     string      `json:"avatar"     ` // AVATAR URL
	Email      string      `json:"email"      ` // EMAIL ADDRESS
	Phone      string      `json:"phone"      ` // PHONE NUMBER
	Gender     int         `json:"gender"     ` // GENDER
	UpdateTime *gtime.Time `json:"updateTime" ` // CREATE AT
	Role       int         `json:"role"       ` // ROLE
	LoginTime  *gtime.Time `json:"loginTime"  ` // LAST LOGIN TIME
	IsCoach    int         `json:"isCoach"    ` //
}
