// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Wallet is the golang structure for table wallet.
type Wallet struct {
	Id     int     `json:"id"     ` // ID
	UserId int     `json:"userId" ` // User ID
	Amount float64 `json:"amount" ` // Money amount
	Status int     `json:"status" ` // Wallet status
}
